# Generated by Django 5.0.6 on 2024-06-26 05:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="product")),
                ("description", tinymce.models.HTMLField()),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
