# Generated by Django 5.0.6 on 2024-06-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Placed", "Order Placed"),
                    ("Shipped", "Order Shipped"),
                    ("InTransit", "In Transit"),
                    ("Delivered", "Order Delivered"),
                    ("Cancelled", "Order Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
